### ISSUE TITLE
Error loading state-dict when using frozen weights. 

### ISSUE THREAD

**Issue by mdiephuis** [facebookresearch/detr#104]
When I try to train the mask heads only, using R50 panoptic, and your checkpoint, with this command:

```
python -m torch.distributed.launch \
 --nproc_per_node=8 \
 --use_env main.py \
 --batch_size 1 \
 --no_aux_loss \
 --frozen_weights weights/detr-r50-panoptic-00ce5173.pth \
 --coco_path /path/to/coco/ \
 --masks \
 --coco_panoptic_path /path/to/panoptic/ \
 --dataset_file coco_panoptic \
 --output_dir /path/to/output/

```
I get an error loading the state-dicts. First lines: 

```
RuntimeError: Error(s) in loading state_dict for DETR:
        Missing key(s) in state_dict: "transformer.encoder.layers.0.self_attn.in_proj_weight", "transformer.encoder.layers.0.self_attn.in_proj_bias", "transformer.encoder.layers.0.self_attn.out_proj.weight", "transformer.encoder.layers.0.self_attn.out_proj.bias", "transformer.encoder.layers.0.linear1.weight", "transformer.encoder.layers.0.linear1.bias", "transformer.encoder.layers.0.linear2.weight", "transformer.encoder.layers.0.linear2.bias", "transformer.encoder.layers.0.norm1.weight", "transformer.encoder.layers.0.norm1.bias", "transformer.encoder.layers.0.norm2.weight",

```
Now, I peaked in the main.py file, and if I replace line 169
`model_without_ddp.detr.load_state_dict(checkpoint['model'])`
simply with:
`model_without_ddp.load_state_dict(checkpoint['model'])`

It seems to start training normally. Any ideas or hints?

**Comment by alcinos** [comment]
Hi @mdiephuis 
Thanks for your interest in DETR.
I think I see what is the issue here: the `--frozen_weights` argument is intended for providing a box only model (for panoptic it has to predict boxes for both things and stuff classes). In what you are doing above, you are passing a box + mask model instead, which indeed will create dictionary loading issues.

Now with your modification you will actually learn everything from the checkpoint including the mask head. Is that what you want/expect? Note that the training will occur only in the mask head though, the rest will be frozen (unlike if you had called --resume instead)
If you want to extract the panoptic box only model and reproduce the training of the mask head, you'll need to do some surgery on the state dict to keep only the detr part. For example (disclaimer, I haven't tested this snippet):
```
model_without_ddp.detr.load_state_dict({k[len("detr."):]: v for k,v  in checkpoint['model'].items() if "detr." in k})
```

Hope this helps.

**Comment by mdiephuis** [comment]
Thanks a lot for your explanation, i'll give it a go.

**Comment by yellowjs0304** [comment]
@mdiephuis Hi, Did you find the way?
I can't understand which layer should be frozen for segmentation task.
Am I should remain the "backbone" part? or "transformer" part??
