### ISSUE TITLE
what is 'bmm' operation in flop count

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#117]
By https://github.com/facebookresearch/detr/issues/110, the flop analysis result contains an operation of type **bmm**:
`    "aten::bmm": bmm_flop_jit,` but I cannot find it in detectron2, could you pls give some information about this operation?

**Comment by fmassa** [comment]
Hi,

`bmm` stands for [batch matrix multiplication](https://pytorch.org/docs/stable/torch.html?highlight=bmm#torch.bmm), and is a legacy function that can be safely be replaced by `matmul`, which is more generic.
The reason why `bmm` was not in the detectron2 default implementation of flop count is that it's not used that much anymore, as we generally use `matmul` now.
But the default implementation of [MultiHeadAttention in PyTorch uses it](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L4108) in a [few different places](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L4130), so we needed to add it as well in order to account for this operation and to more accurately represent the flops for the Transformer.

I believe I have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
