### ISSUE TITLE
Can someone shed some lights into the training set transforms?

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detr#120]
In coco.py, the training images go through a bunch of random transforms... I was wondering if the authors can provide some background on how they were chosen.  I assume they give better performance on Coco but not sure if they help or hurt my custom dataset.  Thanks!

```
                scales = [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]

                T.Compose([
                    T.RandomResize([400, 500, 600]),
                    T.RandomSizeCrop(384, 600),
                    T.RandomResize(scales, max_size=1333),
                ])
```

**Comment by fmassa** [comment]
Hi,

About the first random resizing and flips, it's [very similar to standard resizing for Faster R-CNN](https://github.com/facebookresearch/detectron2/blob/63f11718c68f1ae951caee157b4e10fae4d7e4be/configs/Base-RCNN-FPN.yaml#L41).

The random crops that we do with 0.5 probability do help a bit for the model to combat overfitting, as DETR reasons globally about the image for predicting the objects, so the crops are helpful.
The decisions about the `[400, 500, 600]`  for the new scales and `384, 600` are a bit arbitrary and haven't been tuned much. They are reminiscent from a very early iteration actually, where the `scales` were only `[400, 500, 600]` IIRC.

The reasoning was that we didn't want to have crops that were too small compared to the original image, so that we would still have (with some high enough probability) objects in the moat of the images.

I hope this helps. I'm closing the issue, but let us know if you have further questions.
