### ISSUE TITLE
If i don't have the seg

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/detr#133]
https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/models/detr.py#L47
Why are there two inputs? Does the mask in this line of code refer to the seg information? If I don't have this information, how do I change it?

**Comment by alcinos** [comment]
Hi,

This is not a segmentation mask, this is a padding mask which contains 1 on pixels that were added due to padding when batching images of different sizes, and 0 otherwise.
It is normally created during batching, see https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/util/misc.py#L283-L300

I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
