### ISSUE TITLE
Bug in official Colab implementation II

### ISSUE THREAD

**Issue by Mastemace** [facebookresearch/detr#170]
Hi,
you closed my issue #168 (Sorry I do not know how to reopen it) with the claim it is duplicate and told "This works fine if you clamp the image to a max size of 1333.".

That is not fully correct. The COCO image I'm reporting you has the size of (500,169) so it is obvious the reason is different than the size.
Can you please fix it?

**Comment by fmassa** [comment]
Hi,

In the notebook we have the following transform
```python
# standard PyTorch mean-std input image normalization
transform = T.Compose([
    T.Resize(800),
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
```
which rescales the image so that the minimum size is 800. Note that it does not clamp to a maximum size, as we do in our codebase, see
https://github.com/facebookresearch/detr/blob/9db8be19e76d22ee4ec770cf8ea26301151ec6a8/datasets/transforms.py#L191-L199

So if you take your minimum size of 169 and rescale it to 800, the size which is 500 in the original image resolution will become **2367**, which is larger than the maximum size our demo model supports (which is 1600).

Note that this is an issue with only the demo model, and the original model in torchhub that we provide (and that gives best results) work fine in this situation because it handles this case properly.

We have three options here:
- make the demo code more complicated by adding the `max_size` support for the transform
- assert that the max image size is <= 1600, and if it's not the case, raise an informative error message
- leave this as is

After a few users pointing to the same issue, I'm thinking about option 2, as it still keeps the code simple and the error message is informative. I don't want to go for option 1 because it would diverge from the purpose of the original notebook (which is a **demo** model and we want to keep it as simple as possible).

I believe I have answered your question. I'll be implementing option 2 in the next new minutes

**Comment by fmassa** [comment]
@Mastemace option 2 is implemented in https://github.com/facebookresearch/detr/pull/171
