### ISSUE TITLE
Optimize the transformers

### ISSUE THREAD

**Issue by deepseek** [facebookresearch/detr#19]
@alexholdenmiller @leaderj1001 @alcinos @snyxan 
Thank you for your hard work,

Seeing the transformers learn to understand instances was truly amazing, your work is amazing.
Further research into optimization is vital in-order to make training and inferencing feasible for the 
average person.

Is there a plan for optimizing detr, pruning, distilling, searching for better students, etc... ?

https://github.com/mit-han-lab/hardware-aware-transformers
https://github.com/mit-han-lab/gan-compression
http://news.mit.edu/2020/foolproof-way-shrink-deep-learning-models-0430

**Comment by fmassa** [comment]
Hi,

Thanks for the message.

Indeed, further research to make training for transformers (including DETR) faster is a very important research direction.
Another thing that should definitely be tried in order to increase accessibility is transfer learning, as discussed in https://github.com/facebookresearch/detr/issues/9

As for inference time, DETR is already pretty competitive with Faster R-CNN, as it can run at 28FPS on a V100 using a minimum image size of 800 (max image size 1333).
We believe that by using smaller backbones (for example MobileNetV2) and smaller transformers one could get an even faster inference runtime.

**Comment by deepseek** [comment]
Thanks
