### ISSUE TITLE
longer than 500 epoch results

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#229]
Hi! @fmassa  Thanks for sharing the wonderful work, I'm wondering have you tried training the model for more than 500 epochs, how much AP gain will get, e.g., 600 epchs, 1000epochs?

**Comment by fmassa** [comment]
Hi,

In earlier versions of the implementation we used to train for 900 epochs, and we would get slightly better results. But we reduced the number of epochs to 500 most to make it more accessible and easier to reproduce.
I haven't run the latest version of the model for more than 500 epochs, so I don't have the exact numbers at hand. Maybe some latest changes makes so that improvements are less present.

I believe I've answered your question, and as such I'm closing the issue, but let us know if you have further questions.
