### ISSUE TITLE
Why do the backbone only load pretrained models on the main process?

### ISSUE THREAD

**Issue by cfzd** [facebookresearch/detr#235]
In this code:
https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/backbone.py#L89-L91

Only the model on the main process loads the pretrained weights. Why？

**Comment by fmassa** [comment]
It's not needed, and was added in https://github.com/facebookresearch/detr/pull/60.

The reason is that if you are running the code for the first time in your machine, you'll download the same file multiple times, which could lead to file corruption.

Given that in multi-node training we perform parameter synchronization during the construction of `DistributedDataParallel`, there is no need to download the file multiple times.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.

**Comment by erickim555** [comment]
Just an FYI: I was also worried that only the rank0 process was using the pretrained-on-imagenet backbone weights, and that the other rank1->rankN processes (where N is number of gpu's) were using randomly-init'd backbone weights.
But, this line in the DistributedDataParallel documentation clarifies things, and indeed all ranks will use the pretrained weights. Phew!
```
Construction: The DDP constructor takes a reference to the local module, and broadcasts state_dict() from the process with rank 0 to all other processes in the group to make sure that all model replicas start from the exact same state.
```
https://pytorch.org/docs/master/notes/ddp.html#internal-design
