### ISSUE TITLE
Transformer changed batch size from 100 to 6

### ISSUE THREAD

**Issue by liqi6811** [facebookresearch/detr#240]
Hi team, 

I am passing one image into backbone and transformer, just to get an idea how transformer works. Original image is 100x3x448x448, after backbone got src size 100x2048x28x28, then do Conv2d and get 100x256x28x28 to feed into transformer, but the output size from transformer is 6x100x100x256, my thinking is batch size should not change, but here batch size changed from 100 to 6, how does this work? Appreciate if you could let me know. 

![image](https://user-images.githubusercontent.com/48280760/93664548-24b2a980-fab3-11ea-9f19-690349ebce09.png)

Thank you, 
Ling

**Comment by fmassa** [comment]
Hi,

We return the output of the 6 decoder layers in the model, so that we can easily add intermediate losses. The output of the final decoder layer is obtained by doing `hs[-1]`, which will give as a result `[100, 100, 256]`, in order `[batch_size, num_queries, dim]`.

See in https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/detr.py#L69 that we take the last output of the decoder as the main result.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.
