### ISSUE TITLE
batch size's position is second, is this right your intention?

### ISSUE THREAD

**Issue by EzoBear** [facebookresearch/detr#253]
[https://github.com/facebookresearch/detr/blob/master/models/detr.py](url)

` self.class_embed = nn.Linear(hidden_dim, num_classes + 1)`

```
hs = self.transformer(self.input_proj(src), mask, self.query_embed.weight, pos[-1])[0]
outputs_class = self.class_embed(hs)
outputs_coord = self.bbox_embed(hs).sigmoid()
```

When DETR passed the hs of Transformer's output from DETR to classifier(nn.Linear), I printed as below. If you look at the print result, the batch size(4) is located in the second, and the first is the channel(6). In this case, Classifier well work, but is this really your intention? If it's your intention, please can you explain to me the description?

thank you.

```
print(self.input_proj(src).shape)
print(mask.shape)
print(self.query_embed.weight.shape)
print(pos[-1].shape)
print(hs.shape)
```
```
torch.Size([4, 256, 21, 32])
torch.Size([4, 21, 32])
torch.Size([100,256])
torch.Size([6, 4, 100, 256])
```

**Comment by alcinos** [comment]
Hi @EzoBear 

For `hs` the first dimension is 6 because we return the output of each intermediate layer of the decoder (for auxiliary losses, see paper), and since it has 6 layers that's what you get.
Notice that a bit further down we use `outputs_class[-1]` to retrieve the classes predicted exclusively by the last layer.

I believe I have answered your question and as such I'm closing this.
Feel free to reach out if you have further questions.
