### ISSUE TITLE
Details about how to generate visualization of decoder attention?

### ISSUE THREAD

**Issue by Yvonne0413** [facebookresearch/detr#275]
Thanks so much for this impressive work!

As I go through the paper in detail, I noticed that the decoder attention is fairly local and the attention to those extremities are rather precise. 
Therefore I am curious how **figure 6 on page 12 (Visualizing decoder attention for every predicted object (images from COCO
val set))** is generated?

To be specific:
- What is the exact meaning of the highlighted decoder attention yellow/blue area?
- Which layer of the decoder's intermediate result is represented as those highlighted areas?
- What kind of tools did you use to draw this visualization figures?

Looking forward to your reply and help!
![image](https://user-images.githubusercontent.com/33596363/98091433-690dd380-1ec0-11eb-9361-1a9a86584d7f.png)

**Comment by fmassa** [comment]
Hi,

All the code for visualizing the attentions can be found in our colab notebook in https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb
where you can see the exact code we used, and shows that we use the last layer of the decoder to get the attention maps.

We have some more information about the colormap used in https://github.com/facebookresearch/detr/issues/47

I believe I've answered your question, and as such I'm closing this issue but let us know if you have further questions

**Comment by MarcusNerva** [comment]
@fmassa  Hi there! Thank you for your visualization code! However, I still have some questions. 
![image](https://user-images.githubusercontent.com/37070207/136564195-92912364-deca-4cea-8941-bc813a81b267.png)

Since DETR is built on a transformer and image pixels information is mixed after transfer through transformer-encoder, I think the information of a certain feature tensor output by transformer-encoder can no longer represent the information of the input feature which has the same position in the input tensors sequence. Therefore, I am a little confused by applying attention weight matrix, which is output by model.transformer.decoder.layers[-1].multihead_attn, to visualize. Would you please explain ? Looking forward to your reply!

**Comment by Flyooofly** [comment]
> Hi,
> 
> All the code for visualizing the attentions can be found in our colab notebook in https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb where you can see the exact code we used, and shows that we use the last layer of the decoder to get the attention maps.
> 
> We have some more information about the colormap used in #47
> 
> I believe I've answered your question, and as such I'm closing this issue but let us know if you have further questions

![image](https://user-images.githubusercontent.com/31236750/207823435-7b473e4c-0fb7-441c-888d-988dc0502911.png)
Hello, how is Fig7 drawn? I can't find the relevant code in your open source script.Thx.
