### ISSUE TITLE
Have you tried add instead of concatenation of the x and y positional encoding to construct the position feature?

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/detr#278]
Wonder what will happen.

**Comment by fmassa** [comment]
Hi,

I don't believe we have tried adding the x-y embeddings.
I believe performing the addition instead of concatenation wouldn't be ideal, because the model wouldn't have any information to make the difference between x or y (given that addition is commutative), so it would probably have a harder time predicting coordinates (but to be 100% sure we would need to run an experiment to validate)

I believe I've answered your question and as such I'm closing this issue, but let us know if you have further questions
