### ISSUE TITLE
[d2 wrapper error : AttributeError: 'Trainer' object has no attribute '_data_loader_iter']

### ISSUE THREAD

**Issue by flipflop98** [facebookresearch/detr#282]
In the d2 folder, I got error message as follows:

input cmd : python train_net.py --config configs/detr_256_6_6_torchvision.yaml --num-gpus 4

error msg : 
|     total     | 849949       |              |              |               |              |
[11/08 00:53:59 d2.data.common]: Serializing 118287 elements to byte tensors and concatenating them all ...
[11/08 00:54:02 d2.data.common]: Serialized dataset takes 454.61 MiB
[11/08 00:54:02 d2.data.build]: Using training sampler TrainingSampler
Traceback (most recent call last):
  File "train_net.py", line 155, in <module>
    args=(args,),
  File "/home/svcapp/userdata/detectron2/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/svcapp/userdata/detectron2/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/svcapp/userdata/detr/d2/train_net.py", line 143, in main
    return trainer.train()
  File "/home/svcapp/userdata/detectron2/detectron2/engine/defaults.py", line 413, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/svcapp/userdata/detectron2/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/home/svcapp/userdata/detr/d2/train_net.py", line 49, in run_step
    data = next(self._data_loader_iter)
AttributeError: 'Trainer' object has no attribute '_data_loader_iter'

Why this kinda error happen? Do you have any method to solve this issue?

Thank you in advance.

**Comment by bulyginmv** [comment]
Facing the same issue.

AttributeError: 'Trainer' object has no attribute '_data_loader_iter'

I have been following this tutorial to finetune DETR, and it also crashes at that step. Were some functions changed during update? Does any one know how to fix this issue?

**Comment by bulyginmv** [comment]
As I suspected the issue comes from detectron2 updating its defaults.py file. If you backtrack to the version of the file from September that uses SimpleTrainer instead of TrainerBase, the issue does not seem to appear.

Also, I had to add the _detect_anomaly function:
    
    def _detect_anomaly(self, losses, loss_dict):
        if not torch.isfinite(losses).all():
            raise FloatingPointError(
                "Loss became infinite or NaN at iteration={}!\nloss_dict = {}".format(
                    self.iter, loss_dict
                )
            )

Take out the line:

metrics_dict["data_time"] = data_time

And pass data_time as a self._write_metrics parameter:

self._write_metrics(metrics_dict, data_time=data_time)

That did the trick for me!

But that is of course a workaround, I hope that bug will be fixed eventually.

**Comment by flipflop98** [comment]
I solved the error by changing 
self._data_loader_iter --> self._trainer._data_loader_iter

But I'm not quite sure whether it's correct solution or not! 
Just the error was gone!

**Comment by fmassa** [comment]
Thanks for raising this issue!

@alexander-kirillov should we update the implementation in `detr/d2` to take into account that d2 internals have changed, or should we just change our docs / tutorials to pin to a specific d2 version?

**Comment by ppwwyyxx** [comment]
@fmassa I added #287 that should make it work for both d2 versions. Please take a look! thanks

**Comment by ktobah** [comment]
I am not sure if your fix solves this issue because I am trying to run training and I am having the same issue. I also get:

`'Trainer' object has no attribute '_write_metrics'` and `'Trainer' object has no attribute '_detect_anomaly'`
I have tried a combination of @bulyginmv and @flipflop98 solutions but still doesn't work.

Any thoughts?

I trained a normal detr model for box detection (one class), and now I am trying to use the d2 wrapper for instance segmentation. So, I converted the box checkpoint to a compatible detectron2 model (using your converter.py) and set it on the "FROZEN_WEIGHTS" variable. I set WEIGHTS to "" as suggested in one issue here. I hope my procedure is correct.

<details><summary>Environment info:</summary>
<p>

```python

----------------------  --------------------------------------------------------------------
sys.platform            linux
Python                  3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
numpy                   1.19.1
detectron2              0.3 @/opt/conda/lib/python3.6/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.0
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.1+cu110 @/opt/conda/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
TORCH_CUDA_ARCH_LIST    5.2 6.0 6.1 7.0 7.5 8.0+PTX
Pillow                  8.0.1
torchvision             0.8.2+cu110 @/opt/conda/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.2.post20201218
cv2                     3.4.1
----------------------  --------------------------------------------------------------------

```

</p>
</details>

**Comment by bling-bling-only** [comment]
> 

Hi, I have the same problem as you, has your problem been solved?

**Comment by sseerreenn** [comment]
> > 
> 
> Hi, I have the same problem as you, has your problem been solved?

Do you have any solution for this version of d2?
