### ISSUE TITLE
BUG: when calculate box loss

### ISSUE THREAD

**Issue by urbancaty** [facebookresearch/detr#286]
When form batch, all images will pad zeros to the maximal width and height among the batch.
So, the relative value of target bounding box which vary from 0 to 1 should be corrected when calculate box loss
This deviation will be larger when there is a big difference among image size in a batch

**Comment by fmassa** [comment]
Hi,

This is a good question, thanks for raising it.

We perform padding after normalizing the boxes to be in 0-1 in [the `collate_fn`](https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/util/misc.py#L268-L271). Given that we only pad the right-bottom of the image, the box coordinates don't change in absolute coordinates, but one could say that they change in relative coordinates.

We don't modify the box values in relative coordinates after the padding because of a few reasons:
- we enforce that the predictions are relative to the visible part of the image, and not the padded part
- we mask the padded regions of the image in the transformer (as it is standard to do in NLP), and thus it would be preferable to avoid taking the padded regions into account in other parts of the model

We take special care in the model for this:
- the positional encodings [only consider the regions within the image](https://github.com/facebookresearch/detr/issues/70#issuecomment-641150568)
- the transformer only looks at the regions which are not padded, so we [mask everything which corresponds to pad](https://github.com/facebookresearch/detr/issues/70#issuecomment-641221598)

This means that for the training loss, we don't need to do anything in particular due to the padding, as everything can be compared in terms of the relative coordinates before padding.
But for inference, where we want to map the relative coordinates back to image coordinates, we [need to remove the padding in the image and that's what we do in the `PostProcess` class](https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/detr.py#L267).

I believe I've answered your question and as such I'm closing this issue but let us know if you have further questions.
