### ISSUE TITLE
postprocess

### ISSUE THREAD

**Issue by XiaoJiNu** [facebookresearch/detr#34]
Hi, I didn't see nms in postprocess. Why you don't you nms and could you please explain how does postprocess work?

**Comment by fmassa** [comment]
Hi,

DETR doesn't need NMS by definition, as we explain [in the paper](https://arxiv.org/abs/2005.12872).

Our current postprocessor basically just perform softmax and box conversion (so that it is in `[x0,y0,x1,y1]` format in absolute coordinates).

You can find a video explanation (without having to read the paper) in this youtube video by Yannic Kilcher https://www.youtube.com/watch?v=T35ba_VXkMY

I believe I've answered your question, so I'm closing the issue, but let us know if you have further questions
