### ISSUE TITLE
when detr read the coco dataset

### ISSUE THREAD

**Issue by ohjunee** [facebookresearch/detr#340]
I understand that yolo v3 uses a method of converting json annotation files from coco datasets into text file formats to fit the yolo framework without reading them as they are.

And I know that this is effective in reducing learning time. 
I wonder if DETR can shorten the learning time by changing the format of the json annotation file used by yolo.

**Comment by alcinos** [comment]
Hi @ohjunee 
The answer is most likely no, at least in the default training setting on Coco. The reason is that we currently have a batchsize of 2 images per card, so the data-loading time is extremely negligible.

I believe I have answered your question and as such I'm closing this. Feel free to reach out if you have further concerns.
