### ISSUE TITLE
Problems with detect large objects?

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/detr#4]
Inference result on some images coco:

![image](https://user-images.githubusercontent.com/21303438/83008115-417c2a80-a047-11ea-8789-255b31bdcb0d.png)

**Comment by fmassa** [comment]
Hi,

What is the input image resolution that you are feeding to your model? Note that DETR has been trained on images with min size of 800 and max size of 1333.

**Comment by szagoruyko** [comment]
Hi, I just ran your image (well, together with bounding boxes since I don't have the original) with the demo colab code and got this, there are predictions over what's already been on the image but large predictions are there
![image](https://user-images.githubusercontent.com/4953728/83010312-5b524900-a018-11ea-8024-d35e030a038c.png)

**Comment by fmassa** [comment]
So, thanks a lot @jinfagang for opening the issue.

It turns out that there is a bug in the visualization -- we are using `itertools.chain` to generate the infinite colors for the boxes, but it actually stops once the initial set of colors is used.

We are fixing this in the colab, but by replacing
```python
    colors = itertools.chain(COLORS)
```
with
```python
    colors = COLORS * 100
```
we get (after bumping the threshold a bit as well)
![image](https://user-images.githubusercontent.com/9110200/83011811-cbfa6500-a01a-11ea-9b2e-5311adee002a.png)

**Comment by fmassa** [comment]
Given that I believe we addressed the original issue, I'm closing this, but let us know if you have follow-up questions

**Comment by jinfagang** [comment]
Oh, yeah, I will retest to check this bug, thanks for your guys quick response.
