### ISSUE TITLE
value with not fixed position embedding in encoder

### ISSUE THREAD

**Issue by valencebond** [facebookresearch/detr#415]
Unlike the transformer (proposed in "Attention is all your need"), where value, key, and query are all added with fixed position embedding, values in DETR are not embedded with the position embedding. Is there any insight?  I have searched the issues with the keyword "position embedding" but nothing was found.

**Comment by valencebond** [comment]
I find a solved issue https://github.com/facebookresearch/detr/issues/107#issue-646317390, but the first question is not answered, i.e., " is there any reason for not adding spatial positional encoding to V in both encoder and decoder? This is different from the original transformer implementation and I found no ablation studies in this paper."

**Comment by valencebond** [comment]
Done. solved in https://github.com/facebookresearch/detr/issues/105#issue-645837761

**Comment by alexzeng1206** [comment]
@valencebond After read #105, there is not a intuitive explaination about such operation (i.e., the features are just obtained from v (only contain appearance feature without positional encoding) throughout the process), so I don't know why the final output slot contains spatial information that allows the FFN to predict the bounding box based on it. Can you help to explain where such spatial information comes from?

**Comment by hkproj** [comment]
Hello @wenzhengzeng. As you know from the Transformer theory, adding positional encodings introduces spatial information in the model. If you remember the attention formula, `attention = [softmax(Q*K_t)/sqrt(d_model)] * V`. As you can see, the output of the `softmax `is a tensor with shape `(seq_len, seq_len)`, so you can think of it as a tensor of "scores" (in fact the output of the softmax is used to visualize the attention) that represents the "intensity" of how much two tokens are related to each other and thus "amplifies" some tokens in the V tensor and does not amplify others based on the scores produced by the `softmax`. Since the output of the `softmax `is a matrix that represents the "intensity" of how much two tokens are related to each other, that's also the reason we apply the `-inf` mask to it to disable some interactions when we want to make the model causal. So, the sole goal of the "query" and the "keys" is to decide which value to amplify to produce the attention. This is to say that the positional encoding added only in the query and the keys are enough in deciding which value to "amplify" in the output of the attention. The value tensor is "passive" in this process, so that's why the model performance does not degrade if you don't encode positional encodings in the V matrix. If this is not clear, I suggest you watch the following video from the minute 35:39 onward (https://youtu.be/bCz4OMemCcA?t=2139)

Hope it helps and have a nice day!

**Comment by wenzhengzeng** [comment]
Thank you for your response. I think that one core reason lies in the inherent presence of global or relative positional information within V itself. Otherwise, if  V only contained appearance information, it would not be possible to derive the corresponding object's bbox position based on query features (since the query feature are a linear combination of elements in V). I think that the positional information embedded in V originates from the weighted aggregation (through self/cross-attention) of the relative positional information extracted from CNN, thus resulting in the acquisition of global positional information.

**Comment by hkproj** [comment]
@wenzhengzeng I updated my answer with an hypothesis on why it works even if V does not contain any positional information. Let me quote it:

> You may argue that the V matrix does not contain any positional information. so how can the FFN understand it?
> My hypothesis is that the information captured by the "scores" of the attention is enough to be conveyed to the output of the attention through its multiplication with V.
