### ISSUE TITLE
Any plan about data augmentation

### ISSUE THREAD

**Issue by zhiqwang** [facebookresearch/detr#42]
## ❓ Is there any plan about data augmentation

Hi, DETR teams,

According to the implementation in https://github.com/ultralytics/yolov3/issues/310#issuecomment-546435541, and a similar are discussed in https://github.com/AlexeyAB/darknet/issues/3114#issuecomment-552158041. It seems that such augmentation is helpful to detect smaller size object. I quote Jocher's conclusions below.

> The smaller cars are detected earlier with less blinking and cars of all sizes show better behaved bounding boxes.

I check [`make_coco_transforms`](https://github.com/facebookresearch/detr/blob/b7b62c080d34f76c0069a63afcfb9093213d235c/datasets/coco.py#L115) of this repo, and visualized the augmented images and labels in 
VOC dataset (use the same config of  `make_coco_transforms` here). Since the utilization of `RandomSizeCrop`, all the labels associated to an image may be cropped. (So this repo supports training with no targets in an image? 🤔️)

I want to know whether is there some plan about data augmentation.

Thank you!

**Comment by fmassa** [comment]
Hi,

The current implementation supports a number of data augmentations, including random resizing and random crops.

If I understand it correctly, the mozaic data augmentation that you pointed out is very similar (if not equivalent) to doing random resize on each image. Indeed, in the same mini-batch, we can have images of different resolutions, and it can be customized, so that a very large image could be in the same minibatch as a very small image.

> Since the utilization of RandomSizeCrop, all the labels associated to an image may be cropped. (So this repo supports training with no targets in an image? 🤔️)

Yes, that's correct, we support feeding training images without any annotations (which generally happens with random crops).

I believe I've answered your questions, and as such I'm closing the issue, but let us know if you have further questions.
