### ISSUE TITLE
What is the impact of setting the wrong num_classes

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detr#83]
In detr.py, there is a magic number for num_classes = 20:

`def build(args):
   num_classes = 20 if args.dataset_file != 'coco' else 91`

I only realized this after training on my custom dataset which has 10 classes.  The model seems to converge even with the wrong num_classes set.  What is the impact of setting a higher num_classes in the model?  Will retraining my model with the correct num_classes result in better AP metrics?

**Comment by ruotianluo** [comment]
Even the code itself is using "wrong" num_classes. Coco only has 80 categories; the reason of 91 is because that's the largest category index in the coco annotation file. 
I guess if you train long enough, it is not a big deal.

**Comment by alcinos** [comment]
The only important thing is that num_classes must be higher than the highest class id that you use. If some classes id are unused, it's not an issue, the linear layer responsible for the class prediction will quickly learn to output a probability of 0 for these classes.

To be perfectly complete, we should note that it induces a small waste of weights (in your case 10 classes x embedding size (256) = 2560 useless weights) but unless the number of inactive class is really high it is pretty negligible.

I believe I have answered your question, and as such I'm closing this. If you have further concerns, feel free to reach out.

**Comment by aedirn** [comment]
> To be perfectly complete, we should note that it induces a small waste of weights (in your case 10 classes x embedding size (256) = 2560 useless weights) but unless the number of inactive class is really high it is pretty negligible.

Hi @alcinos , 

I have 12 classes, similar to jackkwok, and am trying to finetune pretrained weights on a custom dataset. I am following guidance from issue #9 and the notebook https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb#scrollTo=tqHkvn1tFyae, but am getting an error loading the class weights. 

_RuntimeError: Error(s) in loading state_dict for DETR:
        size mismatch for class_embed.weight: copying a param with shape torch.Size([92, 256]) from checkpoint, the shape in current model is torch.Size([13, 256])._ 

Looks like this is because the pretrained weights has 91 classes but my model only has 12. How can I resolve this error and finetune on pretrained weights, hopefully without wasting the weights of (91-12) classes?
